apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nginx-ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
spec:
  # Secret names are always required.
  secretName: nginx-cert-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
    - myorg
  commonName: nginx-ssl
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  # At least one of a DNS Name, USI SAN, or IP address is required.
  dnsNames:
    - nginx-ssl
    - nginx-ssl.avi.tkg-vsp-lab.hyrulelab.com
  # Issuer references are always required.
  issuerRef:
    name: nginx-ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io