#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"VSphereMachineTemplate"}),expects="1+"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
spec:
  template:
    spec:
    #@overlay/match missing_ok=True
    #@ if data.values.TAGS != None:
      #@ tags = data.values.TAGS.split(",")
      #@overlay/match missing_ok=True
      tagIDs:
      #@ for i in range(len(tags)) :
        - #@ tags[i]
      #@ end
    #@ end
