apiVersion: run.tanzu.vmware.com/v1alpha3
kind: OSImage
metadata:
  name: v1.25.7---vmware.2-tkg.1-windows
spec:
  image:
    ref:
      template: /Datacenter/vm/tkg/windows-2019-kube-v1.25.7
      version: v1.25.7+vmware.2-tkg.1-windows
    type: ova
  kubernetesVersion: v1.25.7+vmware.2
  os:
    arch: amd64
    name: windows
    type: windows
    version: "2019"