apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logspewer
  labels:
    app: logspewer
spec:
  selector:
    matchLabels:
      app: logspewer
  template:
    metadata:
      labels:
        app: logspewer
    spec:
      containers:
      - name: logspewer
        image: harbor.h2o-4-1056.h2o.vmware.com/tkg/logspewer:latest
        env:
        - name: INTERVAL_IN_SECONDS
          value: "10"
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - value: windows
          key: os
          operator: Equal
          effect: NoSchedule